consumes:
- application/json
info:
  description: Maintaining users database for bookstore_users-api
  title: A Book Store users api
  version: 1.0.0
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"

definitions:
  User:
    type: object
    required:
      - first_name
      - last_name
      - email
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      first_name:
        type: string
        minLength: 1
      last_name:
        type: string
        minLength: 1
      email:
        type: string
        minLength: 1
      date_created:
        type: string
        minLength: 1
        readOnly: true
  RestErr:
    type: object
    required:
      - message
    properties:
      message: 
        type: string
        minLength: 1
      status:
        type: string
        minLength: 1
      code:
        type: string
        minLength: 1

paths:
  /users/{user_id}:
    get:
      operationId: "getUserById"
      tags:
        - "get user by id"
      parameters:
        - name: "user_id"
          in : "path"
          description: "id of the user"
          required: true
          type: "integer"
      responses:
          200: 
            description: "user fetched successfully"
            schema:
              $ref: "#/definitions/User"
          default:
            description: "error response"
            schema:
              $ref: "#/definitions/RestErr"

